// src/styles/theme.js
export const lightTheme = {
  background: "#ffffff",
  text: "#000000",
  sidebarBg: "#f8f8f8",
  borderBg: "#dadada",
  sideBtnBg: "#e2e2e2",
  scrollBar: "#a3a3a3",
  scrollBg: "#ffffff",
  calendarBg: "#fcfcfc",
  calendarOutRangeBg: "#f3f3f3",
  calendarToolbarBg: "#f9f9f9",
  calendarHeaderBg: "#fafafa",
  calendarHeaderText: "#111",
  calendarBorder: "#dadada",
  calendarDateText: "#111",
  otherText: "#b8b8b8",
};

export const darkTheme = {
  background: "#2e2e2e",
  text: "#ffffff",
  sidebarBg: "#2b2b2b",
  borderBg: "#2b2b2b",
  sideBtnBg: "#969696",
  scrollBar: "#727272",
  scrollBg: "#444444",
  calendarBg: "#5f5f5f",
  calendarOutRangeBg: "#4e4e4e",
  calendarToolbarBg: "#444",
  calendarHeaderBg: "#3a3a3a",
  calendarHeaderText: "#acacac",
  calendarBorder: "#8d8d8d",
  calendarDateText: "#cfcfcf",
  otherText: "#202020",
};
